<?php
/**
 * MysqlKind
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;
use \Vented\EnhanceApiLaravel\Client\ObjectSerializer;

/**
 * MysqlKind Class Doc Comment
 *
 * @category Class
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MysqlKind
{
    /**
     * Possible values of this enum
     */
    public const MYSQL80 = 'mysql80';

    public const MYSQL81 = 'mysql81';

    public const MARIA_DB_LTS = 'mariaDbLts';

    public const MARIA_DB11 = 'mariaDb11';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MYSQL80,
            self::MYSQL81,
            self::MARIA_DB_LTS,
            self::MARIA_DB11
        ];
    }
}


