<?php
/**
 * WebsiteKind
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;
use \Vented\EnhanceApiLaravel\Client\ObjectSerializer;

/**
 * WebsiteKind Class Doc Comment
 *
 * @category Class
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebsiteKind
{
    /**
     * Possible values of this enum
     */
    public const NORMAL = 'normal';

    public const CONTROL_PANEL = 'controlPanel';

    public const PHP_MY_ADMIN = 'phpMyAdmin';

    public const ROUNDCUBE = 'roundcube';

    public const STAGING = 'staging';

    public const SERVER_HOSTNAME = 'serverHostname';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NORMAL,
            self::CONTROL_PANEL,
            self::PHP_MY_ADMIN,
            self::ROUNDCUBE,
            self::STAGING,
            self::SERVER_HOSTNAME
        ];
    }
}


