<?php

/**
 * CloneStatus
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;

/**
 * CloneStatus Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class CloneStatus
{
    /**
     * Possible values of this enum
     */
    public const CLONING_WEBSITE = 'cloningWebsite';

    public const CLONING_DATABASES = 'cloningDatabases';

    public const CLONING_HOME_DIR = 'cloningHomeDir';

    public const SUCCEEDED = 'succeeded';

    public const FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLONING_WEBSITE,
            self::CLONING_DATABASES,
            self::CLONING_HOME_DIR,
            self::SUCCEEDED,
            self::FAILED,
        ];
    }
}
