<?php

/**
 * DnsRecordKind
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;

/**
 * DnsRecordKind Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class DnsRecordKind
{
    /**
     * Possible values of this enum
     */
    public const A = 'A';

    public const AAAA = 'AAAA';

    public const CNAME = 'CNAME';

    public const TXT = 'TXT';

    public const SPF = 'SPF';

    public const SRV = 'SRV';

    public const NS = 'NS';

    public const MX = 'MX';

    public const PTR = 'PTR';

    public const DS = 'DS';

    public const CAA = 'CAA';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::A,
            self::AAAA,
            self::CNAME,
            self::TXT,
            self::SPF,
            self::SRV,
            self::NS,
            self::MX,
            self::PTR,
            self::DS,
            self::CAA,
        ];
    }
}
