<?php
/**
 * LicenceStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;
use \Vented\EnhanceApiLaravel\Client\ObjectSerializer;

/**
 * LicenceStatus Class Doc Comment
 *
 * @category Class
 * @description Enhance Licence status
 * @package  Vented\EnhanceApiLaravel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LicenceStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'active';

    public const CANCELLED = 'cancelled';

    public const SUSPENDED = 'suspended';

    public const TRIAL = 'trial';

    public const UNPAID = 'unpaid';

    public const UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::CANCELLED,
            self::SUSPENDED,
            self::TRIAL,
            self::UNPAID,
            self::UNKNOWN
        ];
    }
}


