<?php

/**
 * Role
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;

/**
 * Role Class Doc Comment
 *
 * @category Class
 *
 * @description The role of the member in the organization.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class Role
{
    /**
     * Possible values of this enum
     */
    public const OWNER = 'Owner';

    public const SUPER_ADMIN = 'SuperAdmin';

    public const BUSINESS = 'Business';

    public const SITE_ACCESS = 'SiteAccess';

    public const SUPPORT = 'Support';

    public const SYSADMIN = 'Sysadmin';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OWNER,
            self::SUPER_ADMIN,
            self::BUSINESS,
            self::SITE_ACCESS,
            self::SUPPORT,
            self::SYSADMIN,
        ];
    }
}
