<?php

/**
 * ServerMigrationSettingsAuthType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;

/**
 * ServerMigrationSettingsAuthType Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class ServerMigrationSettingsAuthType
{
    /**
     * Possible values of this enum
     */
    public const WHM_TOKEN = 'whmToken';

    public const CPANEL_TOKEN = 'cpanelToken';

    public const BASIC = 'basic';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WHM_TOKEN,
            self::CPANEL_TOKEN,
            self::BASIC,
        ];
    }
}
