<?php

/**
 * ServiceKind
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.9.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vented\EnhanceApiLaravel\Client\Model;

/**
 * ServiceKind Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class ServiceKind
{
    /**
     * Possible values of this enum
     */
    public const CONTROLD = 'controld';

    public const ORCHD = 'orchd';

    public const AUTHD = 'authd';

    public const LOGD = 'logd';

    public const SGED = 'sged';

    public const BKUPD = 'bkupd';

    public const MYSQLCD = 'mysqlcd';

    public const DNSCD = 'dnscd';

    public const FILERD = 'filerd';

    public const FTPCD = 'ftpcd';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTROLD,
            self::ORCHD,
            self::AUTHD,
            self::LOGD,
            self::SGED,
            self::BKUPD,
            self::MYSQLCD,
            self::DNSCD,
            self::FILERD,
            self::FTPCD,
        ];
    }
}
